apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
  namespace: test
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: docker.jamf.build/echo-server:1.0.0
        imagePullPolicy: Always
        name: echo-server
