apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  labels:
    app: echo
spec:
  rules:
  - host: echo.staging.jamf.build
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: http
